global:
  scrape_interval: 15s

scrape_configs:
  - job_name: containers

    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      - source_labels: [__meta_docker_container_label_metrics_enable]
        action: keep
        regex: true

      - source_labels: [__meta_docker_container_label_metrics_job]
        target_label: job

      - source_labels: [__address__, __meta_docker_container_label_metrics_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

      - source_labels: [__meta_docker_container_label_metrics_scheme]
        action: replace
        regex: (https?)
        target_label: __scheme__

      - source_labels: [__meta_docker_container_label_metrics_path]
        action: replace
        regex: (.+)
        target_label: __metrics_path__

      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container

      - regex: __meta_docker_container_label_app_(.+)
        action: labelmap
        replacement: $1

  - job_name: comin
    static_configs:
      - targets: ["host.containers.internal:4243"]
        labels:
          node: harpy
